### ISSUE TITLE
CI/CD Action

### ISSUE THREAD

**Issue by Zjjc123** [eastlakehs/community-service-tracker#11]
Set up automatic and continuous integration and deployment with GitHub actions.

**Comment by daniel-sudz** [comment]
How about we deploy to github pages for staging/preview and then deploy to firebase for production? Because the problem is that the CI/CD will run on every pull which means that anyone could potential deface the website.

**Comment by Zjjc123** [comment]
Why would it be on every pull?

**Comment by daniel-sudz** [comment]
Github actions staging done, need final deploy

**Comment by daniel-sudz** [comment]
@Zjjc123 Note: I'm gonna change the root domain to / in the package.json since I'm gonna use a custom domain.

**Comment by Zjjc123** [comment]
@daniel-sudz Probably need to clean up github pages

**Comment by daniel-sudz** [comment]
#35

**Comment by daniel-sudz** [comment]
We should add some kind automatically screenshot generation for different devices. Idk how to do this though, maybe some kind of selenium.
