### ISSUE TITLE
Keep a consistent capitlization in the repo folder names

### ISSUE THREAD

**Issue by Zjjc123** [eastlakehs/community-service-tracker#124]
I vote for all lower case @daniel-sudz 

can use command `git config core.ignorecase false` to keep track of capitalization to fix name

**Comment by daniel-sudz** [comment]
@Zjjc123 do you also want to do subfolders? 
https://github.com/eastlakehs/community-service-tracker/tree/master/firebase

**Comment by daniel-sudz** [comment]
Also https://github.com/eastlakehs/community-service-tracker/tree/master/website/src

**Comment by Zjjc123** [comment]
@daniel-sudz yeah will open another pr
