### ISSUE TITLE
Forking is disabled

### ISSUE THREAD

**Issue by theTisch21** [eastlakehs/community-service-tracker#128]
**Is your feature request related to a problem? Please describe.**  
I wanted to test something with GitHub actions to speed up your CI workflow by caching a directory. I didn't want to directly poke at the live repo, so I was going to fork it and test it there using a self-hosted runner (To avoid paying for github's runners). However, forking is disabled.

**Describe the solution you'd like**  
I'd like for forking to be enabled

**Describe alternatives you've considered**  
I could download the entire repo and re-upload it to my own account, but pull requesting from it would be a pain. I could try it using a new branch on this repo, but I'm worried that I will mess something up in the live system.

**Additional context**  
Forking would not reveal any repo secrets, so there is no risk of a fork messing with the live system (Unless there's an API key lying around in the source code, which would be a terrible idea)

**Comment by daniel-sudz** [comment]
@theTisch21 converted repo to public, you should be able to fork now. Private API keys should be only in the github secrets and github should auto-manage that on PRs/forks.
