### ISSUE TITLE
Add a Spot to Add Pictures + a Notes Section

### ISSUE THREAD

**Issue by davidvel25** [eastlakehs/community-service-tracker#141]
**Is your feature request related to a problem? Please describe.**
I really like using this community service tracker as my UNIVERSAL tracker. It can store as many events as needed, and it doesn't reset after the school year ends. It would be great if you could add a section when submitting community service hours to allow pictures to be attached since most community service-based clubs ask for proof by picture. I can store the pictures in this community service tracker until I need to retrieve them and use them, and this website would be a great place to store these pictures in an organized manner.

**Describe the solution you'd like**
Somewhere on the EHS Community Service tracker, such as below the "Contact Phone Number" Section OR beside the "Date" section, you could add an "Attach a File" Button, which the user can click to add up to 5 images related to that community service event as a PDF, DOCX, PNG, JPEG, or GIF that they can upload. Please make sure that once the pictures have been uploaded, the order of the pictures can be re-arranged so that the user can sort the order of the pictures by importance/what they want their community service officer to view first. Also, the option to delete pictures would also be great in case the user uploads the wrong file on accident (Sometimes some community service trackers don't allow the user to modify the uploads such as delete, sorting, adding more pictures once the user hits "Submit" so flexibility would be appreciated).

**Describe alternatives you've considered**
Adding a Notes Section where the user can type out notes regarding the service they contributed. For example, 
"Did Community Service at {insert location here} with {insert friend's name here} and it was great!" and then in the notes section, the user can paste a OneDrive link to their pictures.

^^^ If the "Attach a File" feature is a plausible solution that isn't too much of a hassle to implement, this "Notes" section where the User can add notes regarding the community service opportunity would also be an excellent thing to add as well.

**Additional context**
I have attached a screenshot to show where the placement of these features would look like: 

![2021-05-01 18_13_00-Window](https://user-images.githubusercontent.com/61363763/116798892-ef3e5780-aaa8-11eb-893f-d732522c80fe.jpg)

![Xr1cak1](https://user-images.githubusercontent.com/61363763/116798896-02512780-aaa9-11eb-921f-7d36a1aceda9.png)

**Comment by theTisch21** [comment]
This is a good idea. I'm not sure how we would get the files into Firebase, but the notes section should be easy to implement. I'll do some testing on my fork https://github.com/thetisch21/community-service-tracker, under the branch `notes-and-files`

**Comment by davidvel25** [comment]
https://github.com/eastlakehs/community-service-tracker/issues/142


Thank you so much,
David Velcsov (he/him/his)

**Comment by daniel-sudz** [comment]
@theTisch21 the proper way would be to store images in firebase store (basically just glorified google cloud storage) and then save the links to the images in the firestore database. 

A lazy way to do it (although honestly valid given the scale) would be to just base64 the images and store them as text in the database (about 30-40% overhead with base64).

**Comment by theTisch21** [comment]
@daniel-sudz I'll test both options. Is there a way to run Firebase locally? Or to create a test instance in the cloud? I don't want to mess with the production database for something like this.

**Comment by daniel-sudz** [comment]
@theTisch21 your easiest option would be to open your own firebase project. You should be able to have access to the free-tiere for firestore/storage without having to enable billing (although you do for cloud functions). 

There is an emulator (https://firebase.google.com/docs/emulator-suite) but it currently does not support firebase storage.

**Comment by daniel-sudz** [comment]
Reference for future: 
Keep costs low by setting cache control to infinity (seems like this a per storage bucket attribute)
https://cloud.google.com/storage/docs/viewing-editing-metadata#edit

API reference: https://cloud.google.com/storage/docs/viewing-editing-metadata#edit

@theTisch21 @davidvel25 @Zjjc123 Could we get some more opinions from inside Key Club asking if this is something that other people want?

**Comment by theTisch21** [comment]
@daniel-sudz I just asked everyone

**Comment by theTisch21** [comment]
If you are here from my post on teams, please "like" this comment if you are interested in this feature

**Comment by theTisch21** [comment]
Here's a PR for a "notes" section: #169

**Comment by daniel-sudz** [comment]
https://user-images.githubusercontent.com/52898838/228423662-9a7f1509-0452-4ad5-97d3-42537278c929.mp4

@davidvel25 @theTisch21 lol it's been 2 years but here it is ig
