### ISSUE TITLE
[ADMIN] Export for Admin

### ISSUE THREAD

**Issue by Zjjc123** [eastlakehs/community-service-tracker#147]
Move /reports to a button on the Admin Dashboard

**Comment by daniel-sudz** [comment]
Should reports be protected to admin only? Currently it's read-only for everyone

**Comment by Zjjc123** [comment]
> Should reports be protected to admin only? Currently it's read-only for everyone

I would think so. Probably a privacy issue.

**Comment by daniel-sudz** [comment]
We need to update the firestore rules then and add a client-side feedback for ```ehs-service.org/report```

**Comment by daniel-sudz** [comment]
@TimofeiK27 you could probably do this: 

Look into https://github.com/eastlakehs/community-service-tracker/blob/master/website/src/components/header/pageHeader.tsx and in the ```signedInstate.admin``` block add as a button to  link to the ```ehs.service/report``` page similar to the other links.
