### ISSUE TITLE
Backup duplication to unaffiliated service

### ISSUE THREAD

**Issue by daniel-sudz** [eastlakehs/community-service-tracker#149]
**Describe the bug**
We currently backup the database on a daily basis to firebase storage with the official google backup script. We should duplicate to a second unaffiliated service. 

I propose encrypting the backup blobs with a strong key (to protect the privacy of our users) and then dumping them to a regular github repo (for simplicity and integration with github actions. )

**Comment by theTisch21** [comment]
@daniel-sudz 
I agree that we should backup somewhere else. 
Alternate solution: What if when using the action to backup the repo, the action takes the database backup file(s) and makes it into an archive, like a zip, 7z, or tarball, then uses the upload-artifact action to upload it. The archives could be encrypted and/or password protected, and we could download them by simply going to the action run and downloading the uploaded artifact. Actions can be scheduled to run every month, week, day, hour, minute, and anywhere in between, so we could customize that easily.

**Comment by daniel-sudz** [comment]
@theTisch21 that would work. Something to keep in mind though: artifacts in GitHub actions are hard-coded to have a retention policy of 90 days. I think that's probably reasonable for us: on the firebase side I setup a retention policy of 30 days (daily backups).

**Comment by daniel-sudz** [comment]
I also couldn't find anything relating to the total size of files allowed in github artifacts although (other than people reporting failures for files greater than 2GB) so we would probably need to monitor this to see if we ever hit a hard limit.
