### ISSUE TITLE
New label(s) for formatting

### ISSUE THREAD

**Issue by theTisch21** [eastlakehs/community-service-tracker#162]
**Is your feature request related to a problem? Please describe.**
I've seen a lot of pull requests and issues lately about the formatting of either the source code or the UI. Currently, It's all grouped under "enhancement"

**Describe the solution you'd like**
It would be nice to be able to group those with a label like "Format", or separate labels, "Code cleanup" and "UI Format", and use the "enhancement" for things like new features.

**Comment by Zjjc123** [comment]
@daniel-sudz I think you added some labels before so organize this however you see fit

**Comment by theTisch21** [comment]
We could also add another label for new features, maybe "new-feature"

**Comment by Zjjc123** [comment]
@theTisch21 made labels. save enhancement for new features
