### ISSUE TITLE
[ADMIN] Edit Bug

### ISSUE THREAD

**Issue by Zjjc123** [eastlakehs/community-service-tracker#165]
View a user &#8594; edit a user &#8594; dashboard &#8594; someone with empty hours &#8594; click on "edit" &#8594; data was persisted.

Not sure if this is the intended functionality

**Comment by daniel-sudz** [comment]
@Zjjc123 this a bug

dispatch ```clearEditState``` from https://github.com/eastlakehs/community-service-tracker/blob/master/website/src/redux/editScreenSlice.ts to address it
