### ISSUE TITLE
Fix Edit Page UI

### ISSUE THREAD

**Issue by Zjjc123** [eastlakehs/community-service-tracker#170]
- Keep the UI for mobile versions
- Utilize the entire screen to minimize scrolling for desktop versions by placing boxes not in a linearly fashion but spread out in x and y direction across the screen.

**Comment by Zjjc123** [comment]
@TimofeiK27 you can look into this too. This is just a simple UI change with CSS and HTML.

**Comment by daniel-sudz** [comment]
For people unfamiliar: flexbox or cssgrid is what you would want for this. Tailwindcss (our pre-processer) has some guides here: https://tailwindcss.com/docs/grid-template-columns

**Comment by TimofeiK27** [comment]
@Zjjc123 I've attached an image of the edit page. Were you envisioning something like this?
![editPage](https://user-images.githubusercontent.com/67656268/117526505-82c8ca00-af7a-11eb-8e6d-15d9b05610e0.PNG)

**Comment by TimofeiK27** [comment]
@Zjjc123 You good with something like this?

![editPage](https://user-images.githubusercontent.com/67656268/117556229-7f394f80-b01b-11eb-9259-8d3d8217ad37.PNG)

**Comment by Zjjc123** [comment]
Looks pretty good!

**Comment by TimofeiK27** [comment]
@Zjjc123 I couldn't figure out how to stretch out the form. I'm still new to typescript and tailwind so I was having some trouble with that.

**Comment by Zjjc123** [comment]
And make sure mobile sure looks good

**Comment by Zjjc123** [comment]
Do you have the code somewhere

**Comment by TimofeiK27** [comment]
I cloned the repo to my computer

**Comment by Zjjc123** [comment]
So the easiest way to do this would be to fork the repo (copy it as your own) and then make those changes and pushing them to that fork. Then me and daniel can both view it and help request or make changes as needed. In the end, you would submit a pull request (a request to merge fix/feature into production) and then we can merge it into master.

Since it's UI changes. Could you make the fork and just copy your code currently over. and then pushing it to the fork on github. I'm not sure how much experience you have with git or github sorry.

**Comment by TimofeiK27** [comment]
I made a fork, and pushed the file.
https://github.com/TimofeiK27/community-service-tracker/commit/4379be0895a057ef1592a0ffe94e87c992d8624f

**Comment by Zjjc123** [comment]
@TimofeiK27 It has something to do with max-w-lg
![image](https://user-images.githubusercontent.com/24723940/117583817-22db3c00-b0be-11eb-8493-6f030381cac0.png)

You can increase the width of the element by changing this class name.

https://tailwindcss.com/docs/max-width
![image](https://user-images.githubusercontent.com/24723940/117583827-3d151a00-b0be-11eb-85a3-ceadfa5ae341.png)

**Comment by Zjjc123** [comment]
Mobile is not very responsive to window size
![image](https://user-images.githubusercontent.com/24723940/117585191-f3303200-b0c5-11eb-9f82-10651ad049b9.png)

**Comment by TimofeiK27** [comment]
Currently working on it. You want it to stay the same how it was for mobile, right?

**Comment by Zjjc123** [comment]
Yeah I think a linear layout for mobile would be great

**Comment by Zjjc123** [comment]
Use responsive design to change UI based on a predetermined screensize
https://tailwindcss.com/docs/responsive-design

**Comment by TimofeiK27** [comment]
Should work as expected now!
https://github.com/TimofeiK27/community-service-tracker/commit/448866a9ff07297e6334214e0a1edf9214a30963

**Comment by Zjjc123** [comment]
Looks good to me. Submit a pull request and we can review it.
