### ISSUE TITLE
Update license

### ISSUE THREAD

**Issue by Zjjc123** [eastlakehs/community-service-tracker#172]
Update year in license? @daniel-sudz

**Comment by Zjjc123** [comment]
Do you just have to change it every year?

**Comment by daniel-sudz** [comment]
@TimofeiK27 see if there is a way to make the year automatically update in the ```LISCENSE``` file in github. If not, just a submit a PR to modify the text to the current year.

**Comment by theTisch21** [comment]
We could setup a workflow to simply check on the first day of each month (Cron would be `0 0 1 * *`) and use the GITHUB_TOKEN environment variable to commit it, or use it to create a PR for us to merge.

**Comment by daniel-sudz** [comment]
@theTisch21 you don't actually need to use the ```GITHUB_TOKEN``` anymore. I think workflow files automatically inherit the proper permissions for committing: 

See https://github.com/daniel-sudz/lzw-lite/blob/master/.github/workflows/publish.yml for reference

**Comment by daniel-sudz** [comment]
Looks like @theTisch21 started some testing in his personal repo so I'm assigning him for now

**Comment by Zjjc123** [comment]
I wrote a python script that would rewrite it @theTisch21 on the `license-update` branch

**Comment by theTisch21** [comment]
@Zjjc123 
I'll add my workflow to your branch and have it run your script. I'll then create a PR
