### ISSUE TITLE
Ambiguity between activity name and orginaization

### ISSUE THREAD

**Issue by theTisch21** [eastlakehs/community-service-tracker#191]
**Is your feature request related to a problem? Please describe.**
I've been confused as to whether to put the activity name or the organization name in the first box on the edit page. Screenshot:
![image](https://user-images.githubusercontent.com/20461232/118373024-5e1bb600-b569-11eb-8e48-d337e8641ef2.png)

**Describe the solution you'd like**
We could split it into two boxes, or change the box to one or the other.

**Describe alternatives you've considered**
Using the one box for both pieces of info, like "Eastlake High School: Wall Decorations" or something like that

**Comment by daniel-sudz** [comment]
Feel free to change it to anything—the line reference is at https://github.com/eastlakehs/community-service-tracker/blob/6e3f7f652cd584241a2f77bdfe75f78ee5e38f7d/website/src/components/edit/edit.tsx#L89
