### ISSUE TITLE
Community Service Hour Form says "Date not selected" even though a date has been selected

### ISSUE THREAD

**Issue by Zortex5** [eastlakehs/community-service-tracker#254]
When I fill out all of the information, including the notes and date and hit the "Log New Activity" button, it says "Date Not Selected" and won't log my hours.

Yesterday, I was able to submit my community service hours easily, but now I am unable to

![image](https://user-images.githubusercontent.com/87163038/176795250-51281247-3c4b-438f-af32-97762b102ec2.png)

This bug was observed on Windows 10 in chrome

**Comment by daniel-sudz** [comment]
@Zortex5 could you retry rn? I broke it 2 hours ago ish and then patched it

**Comment by daniel-sudz** [comment]
@Zjjc123 could you try repro as well should be fixed

**Comment by Zjjc123** [comment]
@daniel-sudz works for me. closing this issue.
