### ISSUE TITLE
Clean Up Tailwind in Repo

### ISSUE THREAD

**Issue by Zjjc123** [eastlakehs/community-service-tracker#31]
**Describe the bug**
CSS fills the repository

**Expected behavior**
- A true display of percentage of different type of code
- No need for unused code

**Screenshots**
![image](https://user-images.githubusercontent.com/24723940/90056668-18f1ed00-dc94-11ea-8920-7283ff3997cc.png)

**Comment by daniel-sudz** [comment]
merge #34
