### ISSUE TITLE
UI for adding volunteer hours and displaying them

### ISSUE THREAD

**Issue by daniel-sudz** [eastlakehs/community-service-tracker#47]
@Zjjc123 I'll do the firebase stuff make the UI itself.

**Comment by Zjjc123** [comment]
@daniel-sudz should we use a library for easy filter's and search

**Comment by Zjjc123** [comment]
@daniel-sudz What do we do with the table branch

**Comment by Zjjc123** [comment]
Closed by https://github.com/eastlakehs/community-service-tracker/pull/60
